# See: https://taskfile.dev/api/

# For generate input command:
# task generate

version: "3"

tasks:
  generate:
    aliases:
      - migrate
    desc: "Generate migrations for the database"
    cmds:
      - go run ./cmd/migrator --storage-path=./storage/sso.db --migrations-path=./migrations